Hotfix/ts 25.fix waybill
Rails-course/trucking pull request #49
Opened 2022-04-18 18:09 UTC by helmy-er

2022-04-19 12:32 UTC, NDragneelL9 requested changes

2022-04-19 14:38 UTC, NDragneelL9 commented
Update seeds.rb with new fields

2022-04-20 14:33 UTC, NDragneelL9 reviewed
Add validations to waybills and routes

2022-04-21 07:13 UTC, MonkeyKingBar-bit approved these changes

2022-04-21 07:13 UTC, MonkeyKingBar-bit commented on app/javascript/components/Driver/Checkpoints.tsx
> +                {checkpointsFields.map((cell) => <StyledTableCell align="right">{cell.title}</StyledTableCell>)}
U need also add key={cell.id} in StyledTableCell, because u use map

2022-04-21 07:13 UTC, MonkeyKingBar-bit commented on app/javascript/components/Search.tsx
> +import {
U can write this in one line

2022-04-21 07:13 UTC, MonkeyKingBar-bit commented on app/javascript/constants/checkpoints.ts
> +    title: 'actione',
Do u mean 'action'?

2022-04-21 10:35 UTC, NDragneelL9 approved these changes

2022-04-21 10:35 UTC, merged