Feature/us 1.2 log in
Rails-course/trucking pull request #5
Opened 2022-02-01 07:04 UTC by Rails-course

2022-02-01 14:15 UTC, NDragneelL9 approved these changes
Great job. In future try to get rid of irrelevant stuff before commiting changes.

2022-02-02 12:42 UTC, NDragneelL9 requested changes
Add error messages to login form.

2022-02-02 15:06 UTC, NDragneelL9 approved these changes

2022-02-02 16:22 UTC, helmy-er commented
Good job.

2022-02-02 16:22 UTC, merged