55 avoid using any
Rails-course/trucking pull request #70
Opened 2022-05-01 13:27 UTC by MonkeyKingBar-bit

2022-05-01 14:55 UTC, NDragneelL9 requested changes
Because we are using TypeScript, i guess its better to create new types for our data objects, like Company, User, Alert, Warehouse etc. and instead of type `object` we would use these types. Also inside arrow functions its better to name variables with full names instead of `x`, `c`, `d`, etc.

2022-05-01 14:55 UTC, NDragneelL9 commented on app/javascript/common/interfaces_types.ts
> +export interface CreateRoutesFormProps {
we renamed Routes into Checkpoints

2022-05-03 01:13 UTC, NDragneelL9 approved these changes

2022-05-04 09:11 UTC, helmy-er approved these changes

2022-05-04 09:12 UTC, merged