Hotfix/lw 3 mailer setup
Rails-course/trucking pull request #85
Opened 2022-05-16 16:01 UTC by MonkeyKingBar-bit

2022-05-16 20:07 UTC, NDragneelL9 approved these changes

2022-05-17 05:28 UTC, helmy-er approved these changes

2022-05-18 07:29 UTC, kel-ln requested changes

2022-05-18 07:29 UTC, kel-ln commented on config/environments/development.rb
> +  # config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
это default url, если его закомментировать во всех ссылках придется указывать значение host

2022-05-18 07:29 UTC, kel-ln commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: 'http://trucking-logistics.herokuapp.com/', port: 3000 }
лучше вынести в файл с настройками ( credentials или .env )

2022-06-21 14:16 UTC, closed without merging